### ISSUE TITLE
Possible refactor to use mdfind

### ISSUE THREAD

**Issue by will-stone** [sindresorhus/app-exists#1]
Hi Sindre,

I've been using a small function to find installed apps in my Electron-based app, Browserosaurus. I thought I'd try replacing my function with your package but using AppleScript to "tell Finder" causes my app to display a Finder access permission dialog. Would you be up for a refactor of your package to avoid this? Here's what I'm using:

```ts
import { execFile } from 'child_process'
import { promisify } from 'util'

const execFileP = promisify(execFile)

async function appExists(nameOrBundleId: string): Promise<boolean> {
  const isBundleId = nameOrBundleId.includes('.')

  const query = isBundleId
    ? `kMDItemContentType == 'com.apple.application-bundle' && kMDItemCFBundleIdentifier == '${nameOrBundleId}'`
    : `kMDItemKind == 'Application' && kMDItemFSName == '${nameOrBundleId}.app'c`

  const { stdout: appPath } = await execFileP('mdfind', [query])

  return Boolean(appPath)
}
```

Let me know if you'd like a PR.

**Comment by sindresorhus** [comment]
Yeah, this package was made before all the recent security theatre in macOS. A PR to use `mdfind` would be lovely. 👍
