### ISSUE TITLE
Multiple App Opened When the App Installed by Other User

### ISSUE THREAD

**Issue by mrbitrary** [sindresorhus/app-exists#8]
Hi, I'm facing an issue when there are multiple user in one mac where every user has their own set of applications.

This might be related to how MacOS works (because Spotlight is facing similar issue), where we can use application installed in another user account.

To fix this, I think this PR (https://github.com/sindresorhus/app-exists/pull/7) could help. cmiiw

Regards,

**Comment by sindresorhus** [comment]
> Hi, I'm facing an issue when there are multiple user in one mac where every user has their own set of applications.

You have not described what the actual issue is.
